stages:
    - build
    - cleanup

build-image:
   stage: build
   before_script:
     - export COMMIT=${CI_COMMIT_SHORT_SHA}
     - export BRANCH=${CI_COMMIT_REF_NAME}
     - TAG="$BRANCH-$COMMIT"
     - echo $TAG
   script: 
    - echo "Building storage-provisioner image"
    - docker build -t ${DOCKER_HUB_REPO}/storage-provisioner:$TAG .
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push ${DOCKER_HUB_REPO}/storage-provisioner:$TAG

cleanup:
  when: always
  stage: cleanup
  only:
    - add-gitlab-build
  script:
     - docker images
     - docker image prune -a --force