stages:
    - build
    - cleanup

build-storage-provisioner:
   image: harshshekhar15/gitlab-runner:v3
   stage: build
   only:
    - add-gitlab-build
   before_script:
     - export COMMIT=${CI_COMMIT_SHORT_SHA}
     - export GOPATH=$HOME/go
     - export PATH=$HOME/go/bin:$PATH
     - mkdir -p $HOME/go/src/github.com/mayadata-io/storage-provisioner
     - rsync -az --delete ${CI_PROJECT_DIR}/ ${HOME}/go/src/github.com/mayadata-io/storage-provisioner/ 
     - cd ${HOME}/go/src/github.com/mayadata-io/storage-provisioner/
   script: 
    - echo "Building storage-provisioner"
    - echo $COMMIT
    - docker build -t ${DOCKER_HUB_REPO}/storage-provisioner:$COMMIT .
    - docker push ${DOCKER_HUB_REPO}/storage-provisioner:$COMMIT

cleanup:
  when: always
  stage: cleanup
  only:
    - add-gitlab-build
  script:
     - rm -rf $HOME/go/src/github.com/mayadata-io/
     - docker images
     - docker image prune -a --force