stages:
    - build
    - cleanup

build-storage-provisioner:
   stage: build
   only:
    - add-gitlab-build
   before_script:
     - mkdir -p $HOME/go/src/github.com/mayadata-io/storage-provisioner
     - rsync -az --delete ${CI_PROJECT_DIR}/ ${HOME}/go/src/github.com/mayadata-io/storage-provisioner/ 
     - cd ${HOME}/go/src/github.com/mayadata-io/storage-provisioner/
     - export COMMIT=${CI_COMMIT_SHORT_SHA}
     - export BRANCH=${CI_COMMIT_REF_NAME}
   script: 
    - echo "Building storage-provisioner"
    - echo $COMMIT
    - docker build -t ${DOCKER_HUB_REPO}/storage-provisioner:$COMMIT .
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push ${DOCKER_HUB_REPO}/storage-provisioner:$COMMIT

cleanup:
  when: always
  stage: cleanup
  only:
    - add-gitlab-build
  script:
     - rm -rf $HOME/go/src/github.com/
     - docker images
     - docker image prune -a --force