# This YAML file contains all RBAC objects that are necessary to 
# run ddp storage provisioner.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ddp-storage-provisioner
  namespace: ddp

---
# Provisioner must be able to work with following resources
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ddp-storage-provisioner
rules:
  - apiGroups: ["ddp.mayadata.io"]
    resources: ["storages"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "create", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ddp-storage-provisioner
subjects:
  - kind: ServiceAccount
    name: ddp-storage-provisioner
    namespace: ddp
roleRef:
  kind: ClusterRole
  name: ddp-storage-provisioner
  apiGroup: rbac.authorization.k8s.io

---
# Provisioner must be able to work with configmaps or leases
# in the current namespace if (and only if) leadership election 
# is enabled
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ddp
  name: ddp-storage-provisioner-cfg
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ddp-storage-provisioner-cfg
  namespace: ddp
subjects:
  - kind: ServiceAccount
    name: ddp-storage-provisioner
    namespace: ddp
roleRef:
  kind: Role
  name: ddp-storage-provisioner-cfg
  apiGroup: rbac.authorization.k8s.io
